services:
  webapp:
    build:
      context: ./project
      dockerfile: ./Dockerfile
    env_file:
      - ./project/.env.container
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # keycloak:
  #   image: quay.io/keycloak/keycloak:26.1.0
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./resources/keycloak:/opt/keycloak/data/import/
  #   environment:
  #     KC_DB: postgres
  #     KC_DB_URL: jdbc:postgresql://database:5432/dev
  #     KC_DB_USERNAME: dev
  #     KC_DB_PASSWORD: dev
  #     KC_DB_SCHEMA: keycloak
  #   command: start-dev --import-realm
  #   depends_on:
  #     - flyway